### ISSUE TITLE
Requires update to node-ipfs-api

### ISSUE THREAD

**Issue by travisperson** [ipfs/ipfs-blob-store#1]
This requires an update to `node-ipfs-api` that is yet published! 

See: https://github.com/ipfs/node-ipfs-api/tree/feat/streams

**Comment by jbenet** [comment]
@travisperson do you need publish access? or wanna PR the streams branch?

**Comment by travisperson** [comment]
Got all that, just need to make sure everything is working first, it's almost ready I think. I'll probably open a PR later today.
