### ISSUE TITLE
immutable or mutable?

### ISSUE THREAD

**Issue by jbenet** [ipfs/ipfs-blob-store#3]
@travisperson (without looking at the code on #2 yet)

- is this a blob store where i can do `put(k, v)` and `v = get(k)` (that is backed by a merkledag), or one where i do `obj = get(ipfsPath)`?
- One thing i'd be looking for is a read only blob store to the ipfs dag. (maybe thats why the test suite doesn't pass? mutability?) 
- Maybe a mutable version can use an ipns key? something like:

    ```js
    var ipnsBlobStore = require('ipns-blob-store')
    var pivateKey = getMyPrivateKey(...)
    
    var ibs = ipnsBlobStore(privateKey) // instance based on name at hash(publicKey)
    ibs.put(k, v)
    v = ibs.get(k)
    ```

- I wonder if the immutable ipfs only blob store is enough for _pulling things out_ for reginabox? cc @bengl

/me takes a look at #2

**Comment by travisperson** [comment]
The `block` store is immutable, #2 is mutable. You can remove keys and overwrite them. It's kind of a hacked together version of ipns, where each time you store a new value it updates the root dag (and soon all the entire path) always preserving the new hash. The hash is stored in the `root_hash` variable as well as passed back with each new blob stored. You can pass back any root hash and read from that state.

**Comment by jbenet** [comment]
ahh so it behaves a bit like the new `ipfs object patch` ? I like that a lot actually.

**Comment by travisperson** [comment]
Ya, soon it will act more like the `ipfs object save` @whyrusleeping was working on as you will be able to dive into the dag structure and update keys anywhere along the path.

**Comment by jbenet** [comment]
hey @travisperson does this fully implement https://github.com/maxogden/abstract-blob-store now?

**Comment by travisperson** [comment]
It does not, as you can't remove keys yet. The second PR allows for this, but it there are a few tests that are not passing completely, which I believe is due to a change in IPFS (as I'm pretty sure they were passing at some point, though maybe not).

I was running `ipfs object stat` on a path `<hash>/linkname`, it appears this doesn't work on master anymore (did this ever work?). To fix this we need to be able to either resolve paths or we'd need to manually traverse the structure in this lib, which is fine.

**Comment by jbenet** [comment]
> I was running ipfs object stat on a path `<hash>/linkname`, it appears this doesn't work on master anymore (did this ever work?).

it did -- https://github.com/ipfs/go-ipfs/issues/1446

**Comment by whyrusleeping** [comment]
https://github.com/ipfs/go-ipfs/pull/1475 <- should fix the issue

**Comment by jbenet** [comment]
so, this might work now?

**Comment by diasdavid** [comment]
@jbenet @whyrusleeping it seems so, or I am missing something, but it does pass successfully all the abstract-blob-store tests

https://github.com/ipfs/ipfs-blob-store/pull/2#issuecomment-141579876

**Comment by diasdavid** [comment]
closing this one, "it works™" :)
