### ISSUE TITLE
Make mfs the only ipfs-blob-store

### ISSUE THREAD

**Issue by diasdavid** [ipfs/ipfs-blob-store#6]
Do we need to keep the `block` and `dag` modes? I feel they were attempts, but now since we have mfs, we are golden, right?

https://github.com/ipfs/ipfs-blob-store/blob/master/index.js#L15-L16

**Comment by travisperson** [comment]
Yep, I say dump them.

**Comment by diasdavid** [comment]
Sweet :) just wanted to make sure!

**Comment by jbenet** [comment]
yep agreed

**Comment by diasdavid** [comment]
done on 0.2.0 :)
