### ISSUE TITLE
add to maxogden/abstract-blob-store

### ISSUE THREAD

**Issue by ralphtheninja** [ipfs/ipfs-blob-store#7]

**Comment by ralphtheninja** [comment]
https://github.com/maxogden/abstract-blob-store/commit/d39f3fd38551345a1d7f1e82de78d09e82d3ae64

**Comment by diasdavid** [comment]
nice! Thank you for remembering to make this happen @ralphtheninja :)

**Comment by ralphtheninja** [comment]
@diasdavid A funny side note. The other day I was thinking "it would be cool with an abstract-blob-store that implemented ipfs" and then I found this repo :D

**Comment by jbenet** [comment]
:heart:

**Comment by ralphtheninja** [comment]
Using ipfs as a backend for dat would be really cool.
